name: Create Adlist

on:
  schedule:
    - cron: "0 3 * * *"
  push:
    branches:
      - adlist
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: production

jobs:
  adlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: "jicedtea/cloudflare-gateway-pihole-scripts"
          ref: "adlist"

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install npm dependencies
        run: npm ci

      - name: Download allowlists
        run: npm run download:allowlist
        env:
          ALLOWLIST_URLS: ${{ vars.ALLOWLIST_URLS }}

      - name: Download blocklists
        run: npm run download:blocklist
        env:
          BLOCKLIST_URLS: ${{ vars.BLOCKLIST_URLS }}

      - name: Create adlist
        run: npm run create-adlist

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'adlist.txt'
          commit_message: Update adlist
          branch: ${{ github.head_ref }}
